--- 
title: "Our Family Cookbook"
author: "Zac, Lauren, Izzy, and Friends"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "Just a cookbook"
---

# Food + Making {-}

>Food lies among those topics that I enjoy thinking about most. When not at work, climbing, running, or riding one of my bikes--but most of the time, even when at work, climbing, running, or riding one of my bikes--I am thinking about food. My interest in ingredients has become more keen since my daughter entered the picture; however, my interest in food (generally) has always been fed by raw, and often delicious, curiosity. -Zac SELDEN

The bulk of those recipes included in this repository are not my own, and many come from family, friends, and colleagues from across the globe. This repository also includes a great number of recipes that I have happened across during countless midnight hours of scavenging internet cooking sites searching for a very specific type of dish (usually something that we have run across in our travels). Through using Git (and GitHub), I can experiment and tinker with each recipe until I get it just right (for us), and---at the end of that journey---can look back through each iterative improvement. In every instance, the original, or initial, commit (init) includes the original recipe and, where relevant, a link to the source. Subsequent commits are added as I edit the text (edit), or alter the original recipe (revise), and the comments on those commits are where changes to the original recipe are detailed.

